language: python
python:
  - "2.7"
# - "3.5"

# command to install dependencies
install: "pip install -r requirements.txt"

# command to build zip
#script: nosetests
script:
  - pwd
  - ls -la
  - zip lambda_hello.zip lambda_hello.py
  - ls -la


